config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'application#index'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: 'sidekiq'
  mount PgHero::Engine, at: 'pghero'

  resources :users, only: [] do
    collection do
      post :become_mediator
      get :public_keys
    end
  end

  resources :transactions do
    member do
      get :start
      post :save_initialized
      get :pay
      post :cancel
      post :complete
      get :deny
      get :accept
      post :save_denied
      get :recover
      post :save_recovered
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :payer, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  belongs_to :mediator, class_name: 'User'

  validates :payer, :receiver, :mediator, :key, presence: true
  validates :payer_id, uniqueness: { scope: [:receiver_id, :mediator_id] }

  validates :key, uniqueness: { scope: [:mediator, :receiver, :payer] }

  validate :valid_mediator

  private

  def valid_mediator
    errors.add('Invalid Mediator') unless mediator.mediator?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :address

  enum status: [:uninitialized, :pending, :needs_mediation, :pending_recovery, :completed,
                :cancelled]

  validates :address, :satoshis, presence: true

  delegate :payer, :receiver, :mediator, to: :address
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :public_key, :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  helper ApplicationHelper

  def index
    @transactions = Transaction.includes(address: [:payer, :mediator, :receiver]).joins(:address)
                               .where('payer_id = :id OR receiver_id = :id OR mediator_id = :id',
                                      id: current_user.id)
  end

  protected

  def render_errors(message, path)
    notice[:error] = message
    redirect_to path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:public_key])
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def index
    @transactions = current_user.transactions
  end

  def new
    @transaction = Transaction.new
    @mediators = User.where(mediator: true)
    @users = User.where(mediator: false).where.not(id: current_user.id)
  end

  def create
    address = find_or_initialize_address(address_params)
    return head :bad_request unless address.save && transaction_params[:satoshis].to_i > 0
    Transaction.create(transaction_params.merge(address_id: address.id))
    head :ok
  end

  def start
    transaction
  end

  def save_initialized
    transaction.update(serialization: params[:serialization], status: :pending)
    head :ok
  end

  def pay
    transaction
  end

  def deny
    transaction
  end

  def save_denied
    transaction.update(serialization: params[:serialization], status: :pending_recovery)
    head :ok
  end

  def recover
    transaction
  end

  def save_recovered
    transaction.update(serialization: params[:serialization], status: :cancelled)
    head :ok
  end

  def accept
    transaction
  end

  def complete
    transaction.update(serialization: params[:serialization], status: :completed)
    head :ok
  end

  def cancel
    transaction.update(status: :needs_mediation)
    redirect_to root_path
  end

  private

  def transaction
    @transaction ||= Transaction.includes(:address).find(params[:id])
  end

  def transaction_params
    params.permit(:satoshis)
  end

  def address_params
    params.permit(:key, :receiver_pk, :payer_pk, :mediator_pk)
  end

  def find_or_initialize_address(parameters)
    receiver = User.find_by_public_key(parameters[:receiver_pk])
    payer = User.find_by_public_key(parameters[:payer_pk])
    mediator = User.find_by_public_key(parameters[:mediator_pk])
    return unless [receiver, payer, mediator].all? { |user| user.present? }
    Address.find_or_initialize_by(
      receiver: receiver, payer: payer, mediator: mediator, key: parameters[:key]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def become_mediator
    current_user.update(mediator: true)
    redirect_to root_path
  end

  def public_keys
    byebug
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/views/application/index.html.slim
.row
  .col-md-6
    h2
      | My Transactions
  .col-md-6
    .col-md-10
    .col-md-2
      = link_to 'Log Out', destroy_user_session_path, class: 'btn btn-default', method: :delete

.row

.row
  table.table.table-hover
    tr.info
      th.text-center #
      th.text-center Payer
      th.text-center Receiver
      th.text-center Mediator
      th.text-center Satoshis
      th
    - @transactions.each do |transaction|
      tr
        th.text-center = transaction.id
        th.text-center = "#{transaction.payer.email} #{(transaction.payer == current_user)? '(me)' : ''}"
        th.text-center = "#{transaction.receiver.email} #{(transaction.receiver == current_user)? '(me)' : ''}"
        th.text-center = "#{transaction.mediator.email} #{(transaction.mediator == current_user)? '(me)' : ''}"
        th.text-center = transaction.satoshis
        th.text-center
          - if transaction.completed?
            | Completed
          - elsif transaction.cancelled?
            | Cancelled
          - elsif transaction.uninitialized?
            - if current_user == transaction.receiver
              = link_to 'Initialize', start_transaction_path(transaction), class: 'btn btn-default'
            - else
              | Uninitialized
          - elsif transaction.pending?
            - if current_user == transaction.payer
              = link_to 'Pay', pay_transaction_path(transaction), class: 'btn btn-success'
              = link_to 'Cancel', cancel_transaction_path(transaction), class: 'btn btn-danger', method: :post
            - else
              | Pending
          - elsif transaction.needs_mediation?
            - if current_user == transaction.mediator
                = link_to 'Accept', accept_transaction_path(transaction), class: 'btn btn-success'
                = link_to 'Deny', deny_transaction_path(transaction), class: 'btn btn-danger'
            - else
              | Waiting for Mediation
          - elsif transaction.pending_recovery?
            - if current_user == transaction.payer
              = link_to 'Recover', recover_transaction_path(transaction), class: 'btn btn-success'
            - else
              | Pending Recovery

.row
  = link_to 'New Transaction', new_transaction_path, class: 'btn btn-default'

app/views/layouts/_google_analytics.html.slim
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'XX-XXXXXXX-X', 'auto');
  ga('send', 'pageview');

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title PaymentEscrow
    = csrf_meta_tags
    = metamagic
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      = render 'layouts/google_analytics'
      - flash.each do |key, value|
        div class=(flash_class(key))
          = value
      = yield

app/views/transactions/accept.html.slim
.row
  h2
    | Accept Transaction

.row
  = hidden_field_tag :transaction_serialized, @transaction.serialization
  .form-group#private-key
    = label_tag :private_key
    = password_field_tag :private_key, nil, class: 'form-control', required: true

  = link_to 'Accept Transaction', '#', class: 'btn btn-primary', id: 'complete-transaction', data: { url: complete_transaction_path(@transaction) }
  = link_to 'Back', root_path, class: 'btn btn-default'

app/views/transactions/deny.html.slim
.row
  h2
    | Deny Transaction

.row
  = hidden_field_tag :address_key, @transaction.address.key
  = hidden_field_tag :receiver_public_key, @transaction.receiver.public_key
  = hidden_field_tag :payer_public_key, @transaction.payer.public_key
  = hidden_field_tag :mediator_public_key, @transaction.mediator.public_key
  = hidden_field_tag :satoshis, @transaction.satoshis
  .form-group#private-key
    = label_tag :private_key
    = password_field_tag :private_key, nil, class: 'form-control', required: true

  = link_to 'Deny Transaction', '#', class: 'btn btn-primary', id: 'deny-transaction', data: { url: save_denied_transaction_path(@transaction) }
  = link_to 'Back', root_path, class: 'btn btn-default'

app/views/transactions/new.html.slim
.row
  h2
    | New Transaction
.row
  .form-group#receiver
    = label_tag :receiver
    = select_tag :receiver_id, options_for_select(@users.collect { |u| [u.email, u.public_key] }), class: 'form-control', required: true
  .form-group#mediator
    = label_tag :mediator
    = select_tag :mediator_id, options_for_select(@mediators.collect { |u| [u.email, u.public_key] }), class: 'form-control', required: true

  .form-group
    = label_tag :satoshis
    = number_field_tag :satoshis, 0, step: 100000, min: 100000, class: 'form-control'

  .form-group
    = label_tag :private_key
    = password_field_tag :private_key, nil, class: 'form-control', placeholder: 'Your own Private Key'

  = hidden_field_tag :payer_id, current_user.public_key

  = link_to 'Create', '#', class: 'btn btn-primary', id: 'new-transaction-submit', data: { url: transactions_path }

  = link_to 'Back', root_path, class: 'btn btn-default'

app/views/transactions/pay.html.slim
.row
  h2
    | Pay Transaction

.row
  = hidden_field_tag :transaction_serialized, @transaction.serialization
  .form-group#private-key
    = label_tag :private_key
    = password_field_tag :private_key, nil, class: 'form-control', required: true

  = link_to 'Pay Transaction', '#', class: 'btn btn-primary', id: 'complete-transaction', data: { url: complete_transaction_path(@transaction) }
  = link_to 'Back', root_path, class: 'btn btn-default'

app/views/transactions/recover.html.slim
.row
  h2
    | Recover Transaction

.row
  = hidden_field_tag :transaction_serialized, @transaction.serialization
  .form-group#private-key
    = label_tag :private_key
    = password_field_tag :private_key, nil, class: 'form-control', required: true

  = link_to 'Pay Transaction', '#', class: 'btn btn-primary', id: 'complete-transaction', data: { url: save_recovered_transaction_path(@transaction) }
  = link_to 'Back', root_path, class: 'btn btn-default'

app/views/transactions/start.html.slim
.row
  h2
    | Initialize Transaction

.row
  = hidden_field_tag :address_key, @transaction.address.key
  = hidden_field_tag :receiver_public_key, @transaction.receiver.public_key
  = hidden_field_tag :payer_public_key, @transaction.payer.public_key
  = hidden_field_tag :mediator_public_key, @transaction.mediator.public_key
  = hidden_field_tag :satoshis, @transaction.satoshis
  .form-group#private-key
    = label_tag :private_key
    = password_field_tag :private_key, nil, class: 'form-control', required: true

  = link_to 'Start Transaction', '#', class: 'btn btn-primary', id: 'save-initialized-transaction', data: { url: save_initialized_transaction_path(@transaction) }
  = link_to 'Back', root_path, class: 'btn btn-default'